name = "mal-lean4"
version = "0.1.0"
defaultTargets = ["step0_repl", "step1_read_print", "step2_eval", "step3_env"]

[[lean_lib]]
name = "MalLean4"
leanOptions = [{ name = "linter.missingDocs", value = true }]

[[lean_exe]]
name = "step0_repl"
root = "MalLean4.Step0Repl"

[[lean_exe]]
name = "step1_read_print"
root = "MalLean4.Step1ReadPrint"

[[lean_exe]]
name = "step2_eval"
root = "MalLean4.Step2Eval"

[[lean_exe]]
name = "step3_env"
root = "MalLean4.Step3Env"
